on:
  - push
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create reports directory
        run: mkdir reports
      - name: Run JMeter Tests
        uses: ./
        with:
          test-plan-path: ./blazedemo.jmx
          args: "-e -o ./reports/html/"
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
         name: jmeter-results
         path: result.jtl
         if-no-files-found: error
